analytics_dashboard/analytics_dashboard/urls.py
# pylint: disable=line-too-long,no-value-for-parameter
import os

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

from analytics_dashboard import views


admin.autodiscover()

js_info_dict = {
    'packages': ('analytics_dashboard', 'courses',),
}

urlpatterns = patterns(
    '',
    url(r'^$', views.LandingView.as_view(), name='landing'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^status/$', views.status, name='status'),
    url(r'^health/$', views.health, name='health'),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/login/$',
        RedirectView.as_view(url=reverse_lazy('social:begin', args=['edx-oidc']), permanent=False, query_string=True),
        name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    url(r'^accounts/logout_then_login/$', views.logout_then_login, name='logout_then_login'),
    url(r'^test/auto_auth/$', views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^auth/error/$', 'django.views.defaults.server_error', {'template_name': 'auth_error.html'},
        name='auth_error'),
    url(r'^announcements/', include('announcements.urls')),
)

if settings.DEBUG:  # pragma: no cover
    urlpatterns += patterns(
        '',
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    )

    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=import-error

        urlpatterns += patterns(
            '',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )

analytics_dashboard/courses/urls.py
# pylint: disable=no-value-for-parameter

from django.conf.urls import url, patterns

from courses import views

COURSE_URLS = [
    ('enrollment/activity', views.EnrollmentActivityView.as_view()),
    ('enrollment/geography', views.EnrollmentGeographyView.as_view()),
    ('enrollment/demographics/age', views.EnrollmentDemographicsAgeView.as_view()),
    ('enrollment/demographics/education', views.EnrollmentDemographicsEducationView.as_view()),
    ('enrollment/demographics/gender', views.EnrollmentDemographicsGenderView.as_view()),
    ('engagement/content', views.EngagementContentView.as_view()),
    ('csv/enrollment', views.CourseEnrollmentCSV.as_view()),
    ('csv/enrollment_by_country', views.CourseEnrollmentByCountryCSV.as_view()),
    ('csv/enrollment_demographics_age', views.CourseEnrollmentDemographicsAgeCSV.as_view()),
    ('csv/enrollment_demographics_education', views.CourseEnrollmentDemographicsEducationCSV.as_view()),
    ('csv/enrollment_demographics_gender', views.CourseEnrollmentDemographicsGenderCSV.as_view()),
    ('csv/engagement_activity_trend', views.CourseEngagementActivityTrendCSV.as_view()),
]

COURSE_ID_PATTERN = r'(?P<course_id>[^/+]+[/+][^/+]+[/+][^/]+)'

urlpatterns = patterns(
    '',
    url('^$', views.CourseIndex.as_view(), name='index'),

    # Course homepage. This should be the entry point for other applications linking to the course.
    url(r'^{0}/$'.format(COURSE_ID_PATTERN), views.CourseHome.as_view(), name='home')
)


def generate_regex(path):
    return r'^{0}/{1}/$'.format(COURSE_ID_PATTERN, path)


for name, view in COURSE_URLS:
    # Create a new URL pattern. Slashes are valid for paths, but not names. Replace any forward slashes
    # with an underscore.
    urlpatterns += patterns('', url(generate_regex(name), view, name=name.replace('/', '_')))

analytics_dashboard/templates/announcements.html
{% load announcements_tags %}

{% announcements as announcements_list %}

{% with announcements_list|first as announcement %}
  {% if announcement %}
    <div class="announcement-container" data-dismiss-url="{{ announcement.dismiss_url }}"
         data-view="announcement">
      <div class="container">
        {% csrf_token %}
        <a class="dismiss">
          <span aria-hidden="true"><i class="fa fa-times"></i></span><span class="sr-only">Close</span>
        </a>

        <div class="container">
          <div class="row">
            <div class="col-xs-1 col-md-1">
              <div class="icon"><i class="fa fa-bullhorn"></i></div>
            </div>

            <div class="col-xs-9 col-md-9">
              <div class="message">
                <div class="title">{{ announcement.title }}</div>
                <div class="body">{{ announcement.content|safe }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endwith %}

analytics_dashboard/templates/auth_error.html
{% extends "base-error.html" %}

{% load i18n %}

{% block title %}{% trans "Authentication Failed" %} {{ block.super }}{% endblock title %}

{% block error-title %}{% trans "Authentication Failed" %}{% endblock %}
{% block error-copy %}
  {% trans "There was a problem accessing your account. Please try again." %}
  {{ block.super }}
{% endblock %}

{% block buttons %}
  <a href="{% url 'login' %}" class="btn btn-lg btn-primary">
    <i class="ico fa fa-sign-in" aria-hidden="true"></i> {% trans "Try Again" %}
  </a>
  {{ block.super }}
{% endblock %}

analytics_dashboard/templates/base-error.html
{% extends "base_dashboard.html" %}

{% load i18n %}
{% load dashboard_extras %}

{% block view-name %}view-system{% endblock view-name %}

{# These are intentionally left blank. #}
{% block header %}{% endblock %}
{% block lens_navigation %}{% endblock %}
{% block announcements %}{% endblock %}
{% block footer %}{% endblock %}

{% block content-outer %}
  <div class="site-wrapper">

    <div class="site-wrapper-inner">

      <div class="cover-container">

        <div class="masthead clearfix">
          <div class="inner">
            {% include 'brand.html' with class_prefix='masthead' %}
          </div>
        </div>

        <div class="inner cover">
          <h1 class="cover-heading">
            <span class="error-code">{% block error-code %}{% endblock %}</span>
            <span class="error-title">{% block error-title %}{% endblock %}</span>
          </h1>

          <p class="lead error-copy">
              {% block error-copy %}
              If you continue to see this error, use the link below to contact our support team.
              {% endblock error-copy %}
          </p>

          <p class="lead">
            {% block buttons %}
              <a href="{% settings_value 'SUPPORT_URL' %}" class="btn btn-lg btn-primary" data-role="support-link" target="_blank"
                 title="{% trans 'Use our support tool to ask questions or share feedback.' %}">
                <i class="ico fa fa-life-ring" aria-hidden="true"></i>
                {% captureas platform_name %}{% settings_value "PLATFORM_NAME" %}{% endcaptureas %}

                {# Translators: This intention here is that a user clicks a button to contact a support group (e.g. edX Support, or MITx Support). Reorder the placeholder as you see fit. #}
                {% blocktrans %}Contact {{ platform_name }} Support{% endblocktrans %}
              </a>
            {% endblock %}
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

analytics_dashboard/templates/base.html
{% comment %}
Base template pages.
{% endcomment %}

{% load staticfiles %}
{% load compress %}
{% load dashboard_extras %}

<!DOCTYPE html>
<!--[if lte IE 9]><html class="no-js lt-ie10" lang="en"><![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}| {% settings_value 'FULL_APPLICATION_NAME' %}{% endblock title %}</title>

    {% comment %}
    The stylesheets can be either overriden or augmented here.  Make sure to use the block.super if you're
    adding additional stylesheets in your page when extending the base.
    {% endcomment %}

    {% block stylesheets %}
    {% compress css %}
      <link rel="stylesheet" href="{% static 'sass/style-application.scss' %}" type="text/x-scss">
      {% captureas theme_scss %}
        {% settings_value 'THEME_SCSS' %}
      {% endcaptureas %}
      <link rel="stylesheet" href="{% static theme_scss %}" type="text/x-scss">
    {% endcompress %}
    {% endblock %}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>

{% block body %}{% endblock %}
</html>

analytics_dashboard/templates/base_dashboard.html
{% extends "base.html" %}


{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% load dashboard_extras %}
{% load rjs %}


{% block body %}
<body class="{% block view-name %}{% endblock view-name %}" >
<div id="wrap-content-push-footer-sock">
    {% block header %}
      {% include "header.html" %}
    {% endblock header %}

    {% block announcements %}
      {% include "announcements.html" %}
    {% endblock %}

    {% block lens_navigation %}
      {% include "lens-navigation.html" %}
    {% endblock lens_navigation %}

    <div class="container">
        <div class="row">
          {% block content-outer %}
            {#  Translators: Application here refers to the web site/application being used (e.g. the dashboard). #}
            <main class="col-xs-12 main" id="content" aria-label="{% trans "Application" %}">
                <div class="view-head">
                  {% block header-text %}
                    {% if page_title %}
                      <div class="row page-title-outer">
                        <div class="col-md-6 col-xs-12">
                          <h1>{{ page_title }}</h1>
                        </div>
                        <div class="col-md-6 col-xs-12">
                          <div class="page-subtitle">{{ page_subtitle|default_if_none:'' }}</div>
                        </div>
                      </div>
                    {% endif %}
                  {% endblock %}
                </div>

                <div class="view-intro">
                    <p class="lead text-muted intro-text">
                        {% block intro-text %}{% endblock intro-text %}
                    </p>
                </div>

                {% block content %}
                {% endblock content %}
            </main>
          {% endblock %}
        </div>
    </div>

    <!-- Placed at the end of the document so the pages load faster -->
    {% comment %}
    Make sure to add your JS files here.  You'll probably want to use block.super to add to the comment includes rather
    than override them.
    {% endcomment %}

    {# Translation support for JavaScript strings. #}
    <script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>
    <script type="text/javascript">
      window.language = "{{ LANGUAGE_CODE }}";
    </script>

    {# Initial page data passed from view to JS initializer #}
    {% if page_data %}
    <script type="text/javascript">
      var initModelData = {{ page_data|safe }};
    </script>
    {% endif %}

    {% compress js %}
      <script src="{% static 'bower_components/requirejs/require.js' %}"></script>
      <script src="{% static_rjs 'js/config.js' %}"></script>

      {# Note: django-compressor does not recognize the data-main attribute. Load the main script separately. #}
      <script src="{% static_rjs 'js/common.js' %}"></script>
    {% endcompress %}


    {% compress js %}
      {# Note: This block is purposely separated from the one above so that browsers cache the common JS instead of downloading a single, large file for each page. #}
      {% block javascript %}
      {% endblock javascript %}
    {% endcompress %}

  <div id="footer-sock-push"></div>
</div>
{% block footer %}
  <div id="footer-sock">
    {% include "footer.html" with show_feedback=True %}
  </div>
{% endblock footer %}
</body>
{% endblock body %}

analytics_dashboard/templates/brand.html
{% load staticfiles %}
{% load i18n %}
{% load dashboard_extras %}

<a class="{{ class_prefix }}-brand" href="/">
  <div class="{{ class_prefix }}-brand-logo" alt="{% settings_value 'PLATFORM_NAME' %}"></div>
  <span class="{{ class_prefix }}-brand-app">{% settings_value 'APPLICATION_NAME' %}</span>
</a>

analytics_dashboard/templates/chart_tooltip.html
<span class="sr-only">{{tip_text}}</span>
<i class="ico ico-tooltip fa fa-info-circle chart-tooltip has-tooltip" data-toggle="tooltip"
   data-placement="top" data-track-event="edx.bi.tooltip.displayed"
   data-track-category="{{track_category}}" title="{{tip_text}}"></i>

analytics_dashboard/templates/footer.html
{% load i18n %}
{% load dashboard_extras %}

{#  Translators: Application here refers to the web site/application being used (e.g. the dashboard). #}
<footer class="footer" aria-label="{% trans "Application" %}">
  {% if show_feedback %}
  <div class="feedback">
    <div class="container">
      <div class="row">

        {% captureas support_link_start %}
          <a class="support-link" href="{% settings_value 'SUPPORT_URL' %}" target="_blank">{% endcaptureas %}
        {% captureas support_link_end %}</a>{% endcaptureas %}

        {% captureas email_link %}
          <a class="feedback-email" href="mailto:{{ feedback_email }}?Subject=Feedback">{{ feedback_email }}</a>
        {% endcaptureas %}
        {% blocktrans trimmed %}We want this dashboard to work for you! Need help? {{ support_link_start }}Visit our support
          forum{{ support_link_end }}. Comments or suggestions? Email {{ email_link }}.{% endblocktrans %}
      </div>
    </div>
  </div>
  {% endif %}
  <div class="legal">
    <div class="container">
      <div class="row">
        <div class="col-xs-6 col-md-6">
          <a href="{{ terms_of_service_url }}" target="_blank" data-role="tos">
            {% blocktrans %}Terms of Service{% endblocktrans %}
          </a>
          &nbsp;
          <a href="{{ privacy_policy_url }}" target="_blank" data-role="privacy-policy">
            {% blocktrans %}Privacy Policy{% endblocktrans %}
          </a>
        </div>
        <div class="col-xs-6 col-md-6 text-right">
          {% captureas current_year %}{% now "Y" %}{% endcaptureas %}
          {# Translators: The © symbol appears directly before this line. #}
          <p class="copyright">© {% blocktrans %} {{ current_year }} {{ platform_name }}, except where noted, all rights
            reserved. {% endblocktrans %}</p>
        </div>
      </div>
    </div>
  </div>
</footer>

analytics_dashboard/templates/header.html
{% load i18n %}

{% comment %}
Partial: App-wide header element
{% endcomment %}

<header class="navbar navbar-default" role="banner" aria-label="main" id="nav">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
        <span class="sr-only">{% trans 'Toggle navigation' %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      {% include 'brand.html' with class_prefix='navbar' %}
      {% if course_id %}
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'courses:home' course_id=course_id %}" class="navbar-link">{{ course_id }}</a>
        </li>
      </ul>
      {% endif %}
    </div>

    <div class="collapse navbar-collapse" id="main-nav">
      <ul class="nav navbar-nav navbar-right">
        {% if help_url %}
          <li>
            <a id="help" class="navbar-link " data-track-type="click" data-track-event="edx.bi.help.clicked"
               href="{{ help_url }}" target="_blank">{% trans "Help" %}</a>
          </li>
        {% endif %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle active-user navbar-link" data-toggle="dropdown" role="button"
             id="userMenu">
            <i class="ico-user fa fa-graduation-cap" aria-hidden="true"></i>
            <span class="active-user-name">{{ request.user.username }}</span>
            <i class="ico ico-indicator fa fa-caret-down"></i>
          </a>

          <ul class="dropdown-menu active-user-nav" role="menu" aria-labelledby="userMenu">
            <li>
              <a class="active-user-nav-logout" href="{% url 'logout' %}">{% trans "Logout" %}</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- / navbar-collapse -->
  </div>
  <!-- / container -->
</header>
<!-- / navbar -->

analytics_dashboard/templates/landing_lens.html
<div class="col-md-4 col-xs-12">
    <div class="row">
        <div class="col-xs-12">
            <div class="lens-question">{{heading}}</div>
        </div>
        <div class="col-xs-12">
            <div class="lens-summary">
                <p class="lens-description">{{description}}</p>
                <h1><i class="fa {{lens_icon}}" aria-hidden="true"></i> {{lens_name}}</h1>
            </div>
        </div>
    </div>
</div>

analytics_dashboard/templates/lens-navigation.html
{% load i18n %}
{% comment %}
Partial for displaying the lens navigation and the sections within the lenses.
{% endcomment %}

{% if primary_nav_items %}
  {#  Translators: Application here refers to the web site/application being used (e.g. the dashboard). #}
  <nav class="navbar navbar-default lens-nav" role="navigation" aria-label="{% trans "Application" %}">
    <div class="container ">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle navbar-link" data-toggle="dropdown" role="button" id="lensPrimaryMenu">
            <span class="link-label">
            <i class="ico fa {{ primary_nav_item.icon }}" aria-hidden="true"></i>
            {{ primary_nav_item.label }}
            {# Translators: This refers to the active tab/navigation item. #}
            <span class="sr-only">({% trans "Active" %})</span>
            <i class="ico ico-indicator fa fa-caret-down"></i></span>
          </a>

          <ul class="dropdown-menu" role="menu" aria-labelledby="lensPrimaryMenu">
            {% for item in primary_nav_items %}
              <li>
                <a href="{{ item.href }}">
                  <span class="link-label">
                    <i class="ico fa {{ item.icon }}" aria-hidden="true"></i> {{ item.label }}
                  </span>
                </a>
              </li>
            {% endfor %}
          </ul>
        </li>

        {% include "submenu_navigation.html" with nav_items=secondary_nav_items%}
      </ul>
    </div>
  </nav>
{% endif %}

analytics_dashboard/templates/section_error.html
{% load i18n %}
{% load dashboard_extras %}

<div class="row">
    <div class="col-xs-12">
        <div class="col-xs-12 error-section-container">
            <div class="col-xs-1">
                <i data-placement="top" class="fa fa-exclamation-triangle fa-3 error"></i>
            </div>
            <div class="col-xs-11">
                <div class="short-message">
                    {% comment %}Keeping the sentences whole aids in accurate translations.{% endcomment %}
                    {% if content_type == 'chart' %}
                        {% blocktrans %}We are unable to load this chart.{% endblocktrans %}
                    {% elif content_type == 'table' %}
                        {% blocktrans %}We are unable to load this table.{% endblocktrans %}
                    {% elif content_type == 'metrics' %}
                        {% blocktrans %}We are unable to load these metrics.{% endblocktrans %}
                    {% endif%}
                </div>

                <div>
                    {{load_error_message|safe}}
                </div>
            </div>
        </div>
    </div>
</div>

analytics_dashboard/templates/submenu_navigation.html
{% load i18n %}

{% for item in nav_items %}
<li class="{% if item.active %}active{% endif %} nav-section">
    <a href="{{ item.href }}">
        <span class="link-label">
            {{ item.label }}
            {% if item.active %}
                {# Translators: This refers to the active tab/navigation item. #}
                <span class="sr-only">({% trans "Active" %})</span>
            {% endif %}
        </span>
    </a>
</li>
{% endfor %}

analytics_dashboard/templates/summary_point.html
{% load humanize %}

<div class="summary-point text-center">
  <div class="summary-point-wrapper">
    {% with value=value|default_if_none:0 %}
      <div class="summary-point-number" title="{{ value|intcomma }}">{{ value|intcomma|truncatechars:13 }}</div>
    {% endwith %}
    <div class="summary-point-label">{{ label }}</div>
    {% if subheading %}
      <span class="summary-point-note">{{ subheading }}</span>
    {% endif %}
    {% if tooltip %}
      <div class="summary-point-help">
        <span class="sr-only">{{ tooltip }}</span>
        <i data-toggle="tooltip" data-placement="top" title="{{ tooltip }}"
           data-track-event="edx.bi.tooltip.displayed"
           data-track-title="{{ label }}"
           data-track-category="summary"
           class="ico ico-tooltip fa fa-info-circle has-tooltip"></i>
      </div>
    {% endif %}
  </div>
</div>